In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("postings.csv")

In [5]:
df.head(5)

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  object
 16  application_url             87184 non-null   object
 17  application_type            123849 non-null  object
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   object
 21  skills_desc                 2439 non-null    object
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   object
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  object
 26  currency                    36073 non-null   object
 27  compensation_type           36073 non-null   object
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), object(15)
memory usage: 29.3+ MB

In [7]:
tech_df = df[
    df["title"].str.contains(
        "Software Engineer|Software Developer|Data Analyst|Data Scientist|Data Engineer|Machine Learning Engineer|DevOps Engineer|Business Intelligence Analyst",
        case=False,
        na=False
    )
]

In [8]:
tech_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2919 entries, 22 to 123845
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_id                      2919 non-null   int64
 1   company_name                2890 non-null   object
 2   title                       2919 non-null   object
 3   description                 2919 non-null   object
 4   max_salary                  885 non-null    float64
 5   pay_period                  939 non-null    object
 6   location                    2919 non-null   object
 7   company_id                  2890 non-null   float64
 8   views                       2886 non-null   float64
 9   med_salary                  54 non-null     float64
 10  min_salary                  885 non-null    float64
 11  formatted_work_type         2919 non-null   object
 12  applies                     1480 non-null   float64
 13  original_listed_time        2919 non-null   float64
 14  remote_allowed              926 non-null    float64
 15  job_posting_url             2919 non-null   object
 16  application_url             1795 non-null   object
 17  application_type            2919 non-null   object
 18  expiry                      2919 non-null   float64
 19  closed_time                 44 non-null     float64
 20  formatted_experience_level  2093 non-null   object
 21  skills_desc                 17 non-null     object
 22  listed_time                 2919 non-null   float64
 23  posting_domain              1507 non-null   object
 24  sponsored                   2919 non-null   int64
 25  work_type                   2919 non-null   object
 26  currency                    939 non-null    object
 27  compensation_type           939 non-null    object
 28  normalized_salary           939 non-null    float64
 29  zip_code                    2002 non-null   float64
 30  fips                        1853 non-null   float64
dtypes: float64(14), int64(2), object(15)
memory usage: 729.8+ KB

In [9]:
tech_df = tech_df[
    ["title", "company_name", "description", "location", "formatted_experience_level", "formatted_work_type"]
].copy()

In [10]:
tech_df.isna().sum()

title                           0
company_name                   29
description                     0
location                        0
formatted_experience_level    826
formatted_work_type             0
dtype: int64

In [11]:
tech_df.head(15)

,title,company_name,description,location,formatted_experience_level,formatted_work_type
22,Software Engineer,NaN,"Education Bachelor's degree in software, math,...",Los Angeles Metropolitan Area,NaN,Full-time
26,Software Engineer,GOYT,Job Description:GOYT is seeking a skilled and ...,"Denver, CO",NaN,Part-time
181,Senior Software Engineer,StyleAI,"StyleAI is the AI-powered, all-in-one unified ...",San Francisco Bay Area,NaN,Full-time
283,Sr Data Engineer with Kafka,ZenithMinds Inc,Data Engineer with Kafka (W2 Only)💯% Remote\nM...,"Austin, TX",NaN,Full-time
360,Cloud Platform/ Big Data Engineer,"Subaru Research and Development, Inc",About Subaru Research and Development:Do you c...,"Michigan, United States",Entry level,Full-time
366,Data Science Software Engineer,Sovrinti,Company Overview Sovrinti is a full-service en...,United States,NaN,Full-time
367,Data Engineer/ETL,SilverSpace Technologies Inc,"Responsibilities:Develop new features, fix bug...","Hartford, CT",NaN,Contract
373,Flight Software Engineer,Insight Global,Must Haves:10-15 years of experience with C++ ...,"Webster, TX",Mid-Senior level,Full-time
389,Data Analyst,Tenazx Inc,Job Title: Data AnalystDuration: ContractLocat...,"Queens, NY",NaN,Contract
399,Staff Software Engineer (AHT),Northrop Grumman,"At Northrop Grumman, our employees have incred...","Los Angeles, California, United States",Mid-Senior level,Full-time
429,Software Engineer,TRG,*This position is fully onsite and requires sp...,"Westlake, OH",NaN,Full-time
483,Senior Data Engineer/Analyst - Full Time,NaN,"Job Type: Full-Time, Permanent \nResponsibilit...","California, United States",NaN,Full-time
562,DevOps Engineer,LionOrbit Tech Solutions LLC,Summary:The DevOps Engineer will join a Digita...,"Vienna, VA",NaN,Contract
603,Software Engineer in Test Automation,Qentelli,Must Have: · 10 -12 years of experience with v...,"Dallas, TX",NaN,Full-time
663,Machine Learning Engineer,NLB Services,Job Title: Python AI/ MLType: FulltimeLocation...,"Dallas, TX",NaN,Full-time

In [12]:
print(df["description"].iloc[0])

Job descriptionA leading real estate firm in New Jersey is seeking an administrative Marketing Coordinator with some experience in graphic design. You will be working closely with our fun, kind, ambitious members of the sales team and our dynamic executive team on a daily basis. This is an opportunity to be part of a fast-growing, highly respected real estate brokerage with a reputation for exceptional marketing and extraordinary culture of cooperation and inclusion.Who you are:You must be a well-organized, creative, proactive, positive, and most importantly, kind-hearted person. Please, be responsible, respectful, and cool-under-pressure. Please, be proficient in Adobe Creative Cloud (Indesign, Illustrator, Photoshop) and Microsoft Office Suite. Above all, have fantastic taste and be a good-hearted, fun-loving person who loves working with people and is eager to learn.Role:Our office is a fast-paced environment. You’ll work directly with a Marketing team and communicate daily with other core staff and our large team of agents. This description is a brief overview, but your skills and interests will be considered in what you work on and as the role evolves over time.Agent Assistance- Receive & Organize Marketing Requests from Agents- Track Tasks & Communicate with Marketing team & Agents on Status- Prepare print materials and signs for open houses- Submit Orders to Printers & Communicate & Track DeadlinesGraphic Design & Branding- Managing brand strategy and messaging through website, social media, videos, online advertising, print placement and events- Receive, organize, and prioritize marketing requests from agents- Fulfill agent design requests including postcards, signs, email marketing and property brochures using pre-existing templates and creating custom designs- Maintain brand assets and generic filesEvents & Community- Plan and execute events and promotions- Manage Contacts & Vendors for Event Planning & SponsorshipsOur company is committed to creating a diverse environment and is proud to be an equal opportunity employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, gender, gender identity or expression, sexual orientation, national origin, genetics, disability, age, or veteran status.Job Type: Full-time
Pay: $18-20/hour
Expected hours: 35 – 45 per week
Benefits:Paid time offSchedule:8 hour shiftMonday to FridayExperience:Marketing: 1 year (Preferred)Graphic design: 2 years (Preferred)Work Location: In person

In [13]:
print(tech_df["description"].head(10).to_string(index=False))

Education Bachelor's degree in software, math, ...
Job Description:GOYT is seeking a skilled and m...
StyleAI is the AI-powered, all-in-one unified m...
Data Engineer with Kafka (W2 Only)💯% Remote\nMi...
About Subaru Research and Development:Do you ca...
Company Overview Sovrinti is a full-service ene...
Responsibilities:Develop new features, fix bugs...
Must Haves:10-15 years of experience with C++ d...
Job Title: Data AnalystDuration: ContractLocati...
At Northrop Grumman, our employees have incredi...

In [14]:
tech_df.isna().sum()

title                           0
company_name                   29
description                     0
location                        0
formatted_experience_level    826
formatted_work_type             0
dtype: int64

In [15]:
tech_df["description"].str.len().value_counts()

description
1484    39
1503    34
1453    31
1331    20
2431    11
        ..
1505     1
4877     1
4393     1
1039     1
5402     1
Name: count, Length: 2185, dtype: int64

In [16]:
(tech_df == 0).sum()

title                         0
company_name                  0
description                   0
location                      0
formatted_experience_level    0
formatted_work_type           0
dtype: int64

In [17]:
tech_df.duplicated().sum()

np.int64(57)

In [18]:
tech_df[tech_df.duplicated(keep=False)]

,title,company_name,description,location,formatted_experience_level,formatted_work_type
1946,Senior ETL Data Engineer - Reinsurance - Remote,Avesta Computer Services,The ETL Data Engineer will focus on transformi...,United States,Mid-Senior level,Full-time
3298,Data Engineer,Piper Companies,Piper Companies is seeking a Data Engineer to ...,"McLean, VA",Entry level,Full-time
3885,Senior ETL Data Engineer - Reinsurance - Remote,Avesta Computer Services,The ETL Data Engineer will focus on transformi...,United States,Mid-Senior level,Full-time
5668,Data Analyst-VA,ATC,Job Title: Entry Level Business Analyst / Prod...,"Virginia, United States",Entry level,Full-time
5747,Data Analyst-WA,ATC,Job Title: Entry Level Business Analyst / Prod...,"Washington, United States",Entry level,Full-time
...,...,...,...,...,...,...
116029,Senior Software Engineer,Goliath Partners,We're working with a NYC hedge fund looking fo...,New York City Metropolitan Area,Mid-Senior level,Full-time
116114,Senior Software Engineer,Goliath Partners,Goliath Partners has secured an agreement with...,New York City Metropolitan Area,Mid-Senior level,Full-time
116883,Data Scientist,hackajob,hackajob transforms your job search into a per...,"McLean, VA",Mid-Senior level,Full-time
116889,Data Scientist,hackajob,hackajob transforms your job search into a per...,"McLean, VA",Mid-Senior level,Full-time
117255,High Frequency Trading | Senior Software Engineer,Selby Jennings,Senior Senior Engineer (C++)Selby Jennings is ...,"Austin, TX",Mid-Senior level,Full-time

In [19]:
tech_df = tech_df.drop_duplicates()

In [20]:
tech_df.isna().sum()

title                           0
company_name                   29
description                     0
location                        0
formatted_experience_level    816
formatted_work_type             0
dtype: int64